version: '3.9'

services:
  web:
    build: ./django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    environment:
#      - POSTGRES_USER=django_user
#      - POSTGRES_PASSWORD=django_password
#      - POSTGRES_DB=django_db
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "django_user"
      POSTGRES_PASSWORD: "django_password"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#      - postgres_data:/var/lib/postgresql/data/
      - .:/var/lib/postgresql/data2
#    ports:
#      - "5432:5432"
#volumes:
#  postgres_data: